SELECT TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3') AS ts, 'MARK' AS id FROM dual
UNION ALL
SELECT TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'), o.MCH_STOP_MACHNO
  FROM (SELECT a.MCH_STOP_MACHNO, a.MCH_STOP_CODE, a.MCH_STOP_DATE, a.MCH_STOP_SEQ,
               MAX(a.MCH_STOP_DATE) OVER (PARTITION BY a.MCH_STOP_MACHNO) AS mxd,
               MAX(a.MCH_STOP_SEQ)  OVER (PARTITION BY a.MCH_STOP_MACHNO) AS mxs
          FROM TOSADM.MCH_EQ_WORKSTOP a
         WHERE a.MCH_STOP_ENDTIME IS NULL) o,
       TOSADM.CDY_MACHINE m, TOSADM.CDY_MACHINE_JOBSTOP b
 WHERE (o.MCH_STOP_DATE || o.MCH_STOP_SEQ) = (o.mxd || o.mxs)
   AND o.MCH_STOP_MACHNO = m.CDY_MCHN_CODE
   AND m.CDY_MCHN_TYPE IN ('SC','YT','AT')
   AND o.MCH_STOP_CODE = b.CDY_MSTP_CODE AND b.MCHN_TP = m.CDY_MCHN_TYPE
