SELECT TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3') AS ts, 'MARK' AS id FROM dual
UNION ALL
SELECT TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'), m.CDY_MCHN_CODE
  FROM TOSADM.CDY_MACHINE m
 WHERE m.CDY_MCHN_ONOFF = 'O' AND m.CDY_MCHN_TYPE IN ('SC','YT','AT')
   AND NOT EXISTS (SELECT 1 FROM TOSADM.JOB_ORDER_LIST j
                    WHERE j.JOB_ODR_YTNO = m.CDY_MCHN_CODE
                      AND NVL(j.JOB_ODR_YT_STATUS,'X') IN ('A','B','F','R','X','Q'))
